
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 01 18:00:50 GMT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPAREN = 5;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 6;
  public static final int LPAREN = 4;
  public static final int TIMES = 3;
  public static final int EOF = 0;
}

