
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 21 23:20:59 GMT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOPOWER = 35;
  public static final int GTEQ = 12;
  public static final int CHARS = 5;
  public static final int LBRACKET = 14;
  public static final int CHAR = 24;
  public static final int LTEQ = 11;
  public static final int CONCAT = 6;
  public static final int STR = 27;
  public static final int TUPLE = 29;
  public static final int INTEGER = 52;
  public static final int LPAREN = 36;
  public static final int SEMI = 30;
  public static final int REPEAT = 48;
  public static final int INT = 23;
  public static final int MINUS = 32;
  public static final int LISTS = 56;
  public static final int RPAREN = 37;
  public static final int NOT = 18;
  public static final int AND = 20;
  public static final int LT = 9;
  public static final int IN = 2;
  public static final int OR = 19;
  public static final int TDEF = 4;
  public static final int COMMA = 41;
  public static final int BOOL = 25;
  public static final int DIV = 34;
  public static final int UNTIL = 49;
  public static final int PLUS = 31;
  public static final int IF = 44;
  public static final int DOT = 50;
  public static final int ID = 38;
  public static final int BOOLEAN = 54;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int RBRACKET = 15;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int FLOATNUM = 53;
  public static final int EQEQ = 8;
  public static final int FDEF = 39;
  public static final int VOID = 42;
  public static final int EQ = 7;
  public static final int COL = 40;
  public static final int TIMES = 33;
  public static final int ELSE = 46;
  public static final int NOTIN = 3;
  public static final int LBRACE = 16;
  public static final int TUPLES = 57;
  public static final int WHILE = 45;
  public static final int LIST = 28;
  public static final int FLOAT = 26;
  public static final int RBRACE = 17;
  public static final int LEN = 55;
  public static final int STRING = 51;
  public static final int FALSE = 22;
  public static final int GT = 10;
  public static final int DO = 47;
  public static final int NOTEQ = 13;
}

