
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 13 17:03:14 GMT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 34;
  public static final int DIVIDE = 27;
  public static final int GREATERTHANEQUAL = 35;
  public static final int POWER = 28;
  public static final int RIGHTPAREN = 17;
  public static final int NOTEQUAL = 37;
  public static final int PRIVATE = 5;
  public static final int REPEAT = 44;
  public static final int INT = 7;
  public static final int MINUS = 25;
  public static final int LEFTPAREN = 16;
  public static final int LESSTHANEQUAL = 33;
  public static final int NOT = 21;
  public static final int SEMICOLON = 10;
  public static final int AND = 23;
  public static final int LESSTHAN = 32;
  public static final int IN = 29;
  public static final int OR = 22;
  public static final int BOOL = 6;
  public static final int COMMA = 12;
  public static final int CLASS = 2;
  public static final int UNTIL = 45;
  public static final int PLUS = 24;
  public static final int MULTIPLY = 26;
  public static final int IF = 42;
  public static final int ASSIGN = 20;
  public static final int DOT = 13;
  public static final int ID = 3;
  public static final int REALLITERAL = 40;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int EQUAL = 36;
  public static final int BOOLLITERAL = 38;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int NULL = 18;
  public static final int START = 47;
  public static final int CHRLIST = 9;
  public static final int INTLITERAL = 39;
  public static final int REAL = 8;
  public static final int RIGHTBRACE = 15;
  public static final int COLON = 11;
  public static final int ELSE = 43;
  public static final int NOTIN = 30;
  public static final int LEFTBRACE = 14;
  public static final int PUBLIC = 4;
  public static final int STRINGLITERAL = 41;
  public static final int LENGTH = 31;
}

