
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 29 16:09:23 GMT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TUOP = 7;
  public static final int DIVIDE = 49;
  public static final int CHAR = 2;
  public static final int GE = 40;
  public static final int CONCAT = 6;
  public static final int STR = 20;
  public static final int TUPLE = 3;
  public static final int LPAREN = 23;
  public static final int SEMI = 12;
  public static final int REPEAT = 4;
  public static final int INT = 15;
  public static final int INTNUM = 52;
  public static final int MINUS = 48;
  public static final int RPAREN = 24;
  public static final int NOT = 51;
  public static final int AND = 38;
  public static final int OR = 37;
  public static final int IN = 10;
  public static final int TDEF = 19;
  public static final int BOOL = 17;
  public static final int COMMA = 25;
  public static final int GEQ = 42;
  public static final int UNTIL = 5;
  public static final int ASSIGN = 32;
  public static final int IF = 30;
  public static final int EXP = 34;
  public static final int ID = 54;
  public static final int DOT = 50;
  public static final int LE = 39;
  public static final int EOF = 0;
  public static final int RETURN = 47;
  public static final int TRUE = 45;
  public static final int error = 1;
  public static final int FLOATNUM = 53;
  public static final int ADD = 35;
  public static final int NEQ = 44;
  public static final int FDEF = 18;
  public static final int VOID = 22;
  public static final int CHRVALUE = 55;
  public static final int EQ = 43;
  public static final int TIMES = 36;
  public static final int COLON = 33;
  public static final int NOTIN = 11;
  public static final int LBRACE = 26;
  public static final int ELSE = 31;
  public static final int LSQUARE = 13;
  public static final int RSQUARE = 14;
  public static final int WHILE = 29;
  public static final int LIST = 21;
  public static final int FLOAT = 16;
  public static final int RBRACE = 27;
  public static final int LEQ = 41;
  public static final int LEN = 9;
  public static final int STRVALUE = 56;
  public static final int FALSE = 46;
  public static final int TUCL = 8;
  public static final int DO = 28;
}

